GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon

src/rprblender/engine/viewport_engine.py
src/rprblender/ui/__init__.py
src/rprblender/ui/render.py
src/rprblender/ui/view3d.py

PURPOSE
In Cycles the viewport Shading panel is present in Rendered mode as well as in Material Preview mode.
Support similar panel for RPR in Rendered mode.
- Added Shading options panel to the Rendered Viewport mode;
- added RPR panels for Shading and Render Path options in Rendered mode;
- allowed lightning overrides usage in Rendered Viewport mode.

[RPRBLND-1224] Viewport Shading panel in Rendered mode

---

src/bindings/pyrpr/src/pyrpr.py
src/rprblender/engine/render_engine.py
src/rprblender/engine/viewport_engine.py
src/rprblender/export/image.py
src/rprblender/export/world.py
src/rprblender/properties/world.py
src/rprblender/ui/world.py
src/rprblender/utils/__init__.py

PURPOSE
1. When disabling background override even if the file is still loaded, the backplate should not show up in production render. 
2. Backplates should work in viewport render.
3. Code related to backplate could be simplified and improved.
1. Fixed disabling backplate when background override is disabled.
2. Made backplate work in Viewport render.
3. Added "Crop" setting for Backplate panel, which provides option to user to crop background image due to render resolution.
1. Code refactoring:
- simplified image.ImagePixels class, made it to export image including tile.
- moved Backplate class to WorldData internal class as BackplateData. Included its data into comparison of WorldData. Also simplified code in BackplateData and adjusted code world export …

RPRBLND-1338: Back plates does not work correctly 

---

src/rprblender/engine/animation_engine.py
src/rprblender/engine/animation_engine_hybrid.py

PURPOSE
Animation in Full render quality could have memory leak issue which could produce crash. This is because we don't recreate render context for each frame, instead remove all objects from scene and do reexport. Nevertheless recreating render context for RPR and RPR2 isn't expensive. For hybrid it is still expensive.
Fixed animation render in Full render quality described in #4.
Moved AnimationEngine implementation to animation_engine_hybrid.py and set AnimationEngine for RPR and RPR2 be equal to RennderEngine and RenderEngine2.

RPRBLND-1361: Get blender crash with animation render.

---

src/rprblender/properties/render.py
src/rprblender/ui/render.py

EFFECT:  Enable CPU (and CPU + GPU rendering) in RPR 2.0 in UI.  Also update marketing based on asks.
NOTE:  CPU + GPU rendering should have worked previously, but was disabled in UI.

Rpr 2.0 fix cpu and label

---

src/rprblender/nodes/blender_nodes.py

There are a few more modes with three operands that are still missing:
- `SMOOTH_MIN`
- `SMOOTH_MAX`
- `WRAP`
- `COMPARE`

Add support for MULTIPLY_ADD mode of math Cycles node

---

src/rprblender/export/material.py
src/rprblender/export/object.py

PURPOSE
Appended object or material from other blend file can be in conflict with existent object or material with same name, which can be rendered as object or material from current scene.
Fixed rendering objects which were appended from other blend files.
1. Implemented object.key() using object.name_full which is unique over all existed objects included appended (it includes blend file name, if it was appended from another blend file).
2. Implemented material.key() using material.name_full. Also made code improvements there.

RPRBLND-1383: Name collision with collections.

---

src/rprblender/config.py
src/rprblender/engine/render_engine.py
src/rprblender/engine/render_engine_hybrid.py
src/rprblender/utils/athena.py

PURPOSE
Team from automation tests on CIS wants to check Athena data which is transferred to AWS. Therefore they asked to provide possibility not to remove corresponded athena json files after sending.
Added config setting clean_athena_files (True by default), by which we can control removing athena json files after sending statistics.

RPRBLND-1392: Update Athena for Autotests.

---

src/rprblender/engine/viewport_engine.py
src/rprblender/properties/render.py
src/rprblender/ui/render.py

The idea here is to set a "samples per second" for viewport rendering and adapt the resolution of viewport to reach it.  
TODOS:
- I don't quite get all the resolution setting code, and get a crash there.
- We should probably set a hard floor for downresing resolution
- Encorporate viewport denoising?

Adapt viewport resolution to samples per second

---

src/bindings/pyrpr/src/pyrpr_load_store.py

PURPOSE
Exporting tto *.rpr to directories which contains non latin chars produces error:
`UnicodeEncodeError: 'latin-1' codec can't encode characters in position 15-19: ordinal not in range(256)`
Fixed export to *.rpr to directories which contains non latin chars
Fixed by encoding string to utf-8 format.

RPRBLND-1391: Export to *.rpr to directories which contains non latin chars

---

cmd_tools/create_sdk.py
src/bindings/pyrpr/rpr.py
src/bindings/pyrpr/src/pyrprimagefilters.py
src/rprblender/__init__.py
src/rprblender/engine/engine.py
src/rprblender/engine/image_filter.py
src/rprblender/nodes/blender_nodes.py
src/rprblender/properties/view_layer.py
src/rprblender/ui/view_layer.py

PURPOSE
New RIF 1.5.3 is available with some improvements in ML filter using FP16 models.
Updated to new RIF 1.5.3. Made ML filter to use FP16 models, which could speed up denoising process with less memory usage.
- Switching to latest RIF 1.5.3
- adjusted create_sdk.py and rpr.py
- enabled using FP16 models for ML filter
- added call SynchronizeQueue() before ContextExecuteCommandQueue() which is more correct.

RPRBLND-1420: Updating to new RIF 1.5.4

---

src/rprblender/nodes/blender_nodes.py

Possible error in parsing ShaderNodeRGBCurve, more details #83.
`TypeError: 'float' object is not subscriptable`
Fixed possible error in parsing RGB Curve node.
Fixed by using NodeItem.get_channel(), which works with float data value.

RPRBLND-1471: Possible error in parsing ShaderNodeRGBCurve.

---

src/rprblender/properties/view_layer.py

New Core 1.35.5 is available.
Update of core SDK to 1.35.5.
Switched to latest RadeonProRenderSDK submodule. Adjusted const AOV_MATERIAL_ID.

Core 1.35.5 update

---

cmd_tools/create_sdk.py
src/bindings/pyrpr/src/pyrprimagefilters.py

New RIF 1.6.0 is available.
Updating RIF to 1.6.0 version.
Updated RIF submodule, create_sdk.py and API_VERSION calculation.

Update RIF 1.6.0

---

src/rprblender/operators/export_scene.py

After latest core update we missed to rename AOV_MATERIAL_IDX to AOV_MATERIAL_ID in export_scene.py.
Fixed .rpr export after core update.
Renamed AOV_MATERIAL_IDX to AOV_MATERIAL_ID in export_scene.py.

AOV_MATERIAL_ID fix in rpr export after core update.

---

src/RPRBlender.pyproj
src/bindings/pyrpr/src/pyrpr.py
src/bindings/pyrpr/src/pyrpr2.py
src/rprblender/__init__.py
src/rprblender/engine/context.py
src/rprblender/engine/image_filter.py
src/rprblender/engine/render_engine.py
src/rprblender/engine/viewport_engine.py
src/rprblender/engine/viewport_engine_2.py
src/rprblender/properties/view_layer.py
src/rprblender/ui/render.py

RPR 2.0 provides features with update render callback to get intermediate render results during ContextRender and more optimized when using bigger iteration parameter.
Provided new more optimized viewport rendering algorithm for RPR 2.0. 
Enabled denoising for RPR 2.0 in viewport.
1. In pyrpr wrappers:
- added pyrpr2.Context.set_render_update_callback() function to set the callback
- added pyrpr.Context.abort_render()
- set empty PostEffect for pyrpr2
- code improvement in pyrpr2
2. Moved ViewportEngine2 into viewport_engine_2.py.
3. Refactored ViewportEngine to be able to use in ViewportEngine2: 
- splitted _do_sync_render() into _do_sync(), _do_render()
- splitted draw()
4. In ViewportEngine2 _do_render() and draw() were completely rewritten.
5. Enabled denoiser for RPR 2.0 and fixed it …

RPRBLND-1423: Optimize render loop for RPR 2.0

---

src/bindings/pyrpr/src/pyrpr.py
src/bindings/pyrpr/src/pyrpr2.py
src/rprblender/__init__.py
src/rprblender/engine/animation_engine.py
src/rprblender/engine/context.py
src/rprblender/engine/image_filter.py
src/rprblender/engine/render_engine.py
src/rprblender/engine/render_engine_2.py
src/rprblender/properties/render.py
src/rprblender/properties/view_layer.py
src/rprblender/ui/render.py

RPR 2.0 provides features with update render callback to get intermediate render results during ContextRender and more optimized when using bigger iteration parameter.
Provided new more optimized final rendering algorithm for RPR 2.0.
Disabled tile rendering for RPR 2.0, as it works by tiles internally.
Enabled denoising for RPR 2.0 in final render.
1. In pyrpr wrappers:
- added pyrpr2.Context.set_render_update_callback() function to set the callback
- added pyrpr.Context.abort_render()
- set empty PostEffect for pyrpr2
- code improvement in pyrpr2
2. Moved RenderEngine2 into render_engine_2.py. Done there:
- made _render() function to update intermediate render results in separate thread after receiving render update callback.
3. Disabled tile rendering for RPR 2.0 in UI.
4. Enabled …

RPRBLND-1476: Optimize Final render for RPR 2.0

---

src/rprblender/engine/viewport_engine.py
src/rprblender/engine/viewport_engine_2.py
src/rprblender/utils/gl.py

Denoiser in viewport only at last iteration isn't enough, would be good to see denoiser results at intermediate iterations.
Applied denoising in viewport at 4, 8, 16, 32, 64, 96, 128... iterations, not only at last iteration. Increased viewport speed.
1. Applied denoising in viewport at 4, 8, 16, 32, 64, 96, 128... iterations.
2. Improved GLTexture, now it holds image pixels and can be resized during set_image().
3. Increased viewport speed by: 
- with enabled denosier: denosied image is prepared once and is used to draw without getting data from image filter + resolve context doesn't called
- with disabled denoiser: resolve context is called in draw() so it could be called not every iteration.
Denoising is applied in the same thread were rendering is applied. Due to denoiser is applied …

RPRBLND-1416: Enable viewport denoising

---

src/bindings/pyrpr/src/pyhybrid.py

PR #95 produced error in Hybrid, because ContextSetAOVindexLookup produces ERROR_UNIMPLEMENTED exception.
Fixed Hybrid rendering after PR #95.
- Added ERROR_UNIMPLEMENTED to ignore_unsupported attribute.
- Added ignore_unsupported attribute to pyhybrid.Context.set_aov_index_lookup()

RPRBLND-1490: Hybrid causes ContextSetAOVindexLookup to return CoreError

---

README-OSX.md
README.md
run_blender_with_rpr.cmd
run_blender_with_rpr_Ubuntu.sh
run_blender_with_rpr_osx.sh

Rename build methods using BLENDER_28x_EXE to BLENDER_EXE.  Since we can now build with 2.90 etc.
No functional change
DEVELOPERS build scripts may need to be updated

Rename blender 28x exe build variable.

---

src/bindings/pyrpr/src/pyrpr2.py
src/rprblender/engine/context.py
src/rprblender/engine/engine.py
src/rprblender/export/particle.py

Motion blur functionality for RPR 2.0 was integrated in new core with rprShapeSetMotionTransform() and rprShapeSetMotionTransformCount() functions. 
Implemented motion blur for RPR 2.0.
- Implemented pyrpr2.Shape.set_motion_transform(), pyrpr2.AreaLight.set_motion_transform().
- Adjusted Engine.sync_motion_blur() and particle.sync() to use new functionality.
RPR 1 still uses old functionality.

RPRBLND-1520: Move to use Direct transform setting for motion blur

---

BlenderPkg/create_zip_addon.py

We didn't use any zip compression level for zipping plugin installer. Therefore size of plugin took 166MB in Windows. With zip compression the size decreases to 103 MB.
Decreased zip installer plugin size by 40% approximately.
Set compression=zipfile.ZIP_DEFLATED and compresslevel=zlib.Z_BEST_COMPRESSION in creating ZipFile.

Set zip compression level to Z_BEST_COMPRESSION in create_zip_addon.py.

---

src/bindings/pyrpr/src/pyhybrid.py
src/bindings/pyrpr/src/pyrpr.py

This is an old bug (from beginning), which is reproducible on scenes which have material with lot of arithmetic. Memory leak especially noticeable during animation render.
Fixed memory leak during rendering some scenes, which was especially noticeable during animation render.
Done:
- added pyrpr.MaterialNode.delete() which removes all links from material node and deletes node more correctly;
- adjusted pyhybrid.MaterialNode.delete() which just removes links;
- small cleanup in pyrpr.Object.

RPRBLND-1502: Memory leak with specific scene

---

src/bindings/pyrpr/src/pyrpr.py

Possible error after #122: AttributeError:  'CompiledFFI' object has no attribute 'release'
Removed ffi.release() as not necessary.

Fixing possible AttributeError

---

src/rprblender/engine/viewport_engine_2.py

'Preview' option was implemented in latest core 2.0.1.7-final and viewport can be rendered more faster at first iterations. Therefore it make sense to show render results of first iterations during viewport changes.
Implemented showing render results of first iterations during viewport changes for RPR 2.0.
Done:
- set render update callback starting from second iteration
- made getting render result for first iteration in _do_render thread.
- switched RadeonProRenderSDK to 2.0.1.7 final

RPRBLND-1531: Implement 'preview' setting in viewport for RPR2

---

src/rprblender/engine/context.py
src/rprblender/engine/export_engine.py
src/rprblender/engine/render_engine.py
src/rprblender/properties/object.py
src/rprblender/ui/object.py

There are several issues in subdivision settings:
- low subdivision level causes a system crash;
- default subdivision level as 1.0 subdivides mesh so much, which to noticeably slows whole rendering;
- have several blames about misunderstanding of what subdivision level means and why it has values from 0.01 to 10.0 (soft max);
- RPR1 and RPR2 produce so different mesh subdivision in the same subdivision level.
Improved working with subdivision settings: changed behavior of subdivision level as integer value from 0 to 8 (as soft max) and 12 (as max).
- changed behavior of subdivision level as integer value from 0 to 8 (as soft max) and 12 (as max)
- adjusted levels between RPR 1 and RPR 2
- made some code improvements

RPRBLND-1538: Low subdivision level causes a system crash.

---

src/rprblender/engine/viewport_engine_2.py

Using 'preview' rendering mode in viewport produces square artifacts at next iterations.
Fixed viewport rendering artifacts after using 'preview' rendering mode.
Fixed by clearing framebuffers before second iteration disabling intermediate update at second iteration.

RPRBLND-1555: Viewport 'preview' rendering produces square artifacts at next iterations

---

src/rprblender/__init__.py

Wrong binaries were used during merge of develop to master. Provide correct core 2.01.8.1 beta 1 binaries.
- used correct SDK binaries - 2.01.8.1 beta 1.
- switched submodule to latest SDK branch 2.01.8.1 beta 1 version.

Use core 2.01.8.1 beta1

---

src/rprblender/operators/render.py

Links for "Community" and "Bug Reports" buttons in Help/About panel follow to the wrong pages.
Updated links for "Community" and "Bug Reports" buttons in Help/About panel.
Set correct links in rpr.op_open_web_page operator.

Update Help\About link for "Community" and "Bug Reports" buttons

---

RPRBlenderHelper/CMakeLists.txt

PR #168 produces build error on our CIS machines with MacOS, because of required usage of OpenMP for RPRBlenederHelper app. But OpenMP is never used there (probably it was used there long time ago in 1.* plugin) and can be removed.
Removed OpenMP usage from RPRBlenderHelper as not needed.

PRBLND-1626: Fix MacOS build on CIS after applying OpenMP.

---

src/rprblender/export/image.py

Using UDIM tiles could produce error:
`ERROR rpr.init [4913487296]:  set_image_gamma() missing 1 required positional argument: 'rpr_context'`
Error comes from #181.
Fixed possible error with UDIM texture.
Fixed by adding necessary rpr_context argument to set_image_gamma()

RPRBLND-1629: Issue with UDIM tiles

---

src/rprblender/export/world.py

After #178 viewport material preview produces 
```
File "D:\amd-gpuopen\RadeonProRenderBlenderAddon\src\rprblender\export\world.py", line 72, in set_light_rotation
euler = mathutils.Euler((rotation[0], rotation[1], rotation[2] - np.pi / 2))
TypeError: 'NoneType' object is not subscriptable
```
Fixed error in running viewport material preview.
Defining rotation to OverideData in init_from_shading_data().

Fixed error with viewport material preview

---

src/rprblender/engine/context.py
src/rprblender/engine/context_hybrid.py
src/rprblender/engine/viewport_engine.py
src/rprblender/engine/viewport_engine_2.py
src/rprblender/ui/render.py

We should try and improve the viewport rendering speed in Northstar:
1.  Enable viewport scaling
2.  Only resolve color AOV for intermediate iterations. Other AOVs should be resolved only at last iteration for image filter needs.
Applied adaptive viewport resolution for Full render quality. Applied internal optimizations for viewport rendering.
Enabled Adapt Viewport Resoltion option in Viewport & Preview Sampling panel.
1. Moved adaptive resolution code in ViewportEngine to _adapt_resize() function, made it available to use in ViewportEngine2.
2. Overrided _resize() in ViewportEngine2.
3. Implemented algorithm of adaptive resolution in ViewportEngine2._do_render().
4. Enabled UI Adapt Viewport Resoltion option.
5. Improved RPRContext.resolve() with aovs parameter. Optimized resolving at …

RPRBLND-1583: Viewport optimizations for Northstar

---

src/rprblender/engine/viewport_engine.py

Lights power animation shows only the first frame of animation when viewport render start.
Fixed light update during viewport rendering with animated light settings like power, color, etc).
Fixed, by adding bpy.types.Light to sync_update() checking.

RPRBLND-1634: Light power animation not update in realtime.

---

src/rprblender/engine/render_engine.py

This fix relates to #153 #196.
This is hybrid core issue, and probably it'll be fixed in next core. But currently we can do short fix on plugin side.
Fixed exception related to getting stats data in low/medium/hight render quality in final render.
Temporary ignore getting texture sizes with hybrid, until it'll be fixed on hybrid core side.

RPRBLND-1529: Athena issue with Hybrid.

---

src/rprblender/__init__.py
src/rprblender/engine/engine.py

When scene has material with big node tree structure (for example lot of nodes with internal arithmetic) it can be not freed from memory in the end of rendering.
Fixed possible memory leak in final render with scenes with big material node tree.
Fixed by explicit calling stop_render() in the end of render() function.

RPRBLND-1635: Tree creature scene doesn't free memory.

---

src/rprblender/engine/engine.py
src/rprblender/engine/image_filter.py
src/rprblender/engine/viewport_engine.py
src/rprblender/engine/viewport_engine_2.py
src/rprblender/properties/render.py
src/rprblender/ui/render.py

RIF has upscale ML filter, which provides us to render at lower resolution in viewport and upscaling rendered image.
Enabled upscaling in viewport render, which provides faster render at 2-times lower resolution and upscaling rendered image. Added correspondent option in viewport sampling tab.
1. Added class ImageFilterUpscale.
2. Added Engine.upscale_filter and correspondent methods.
3. Added viewport_resolution_upscale property in user settings, added this property in UI in viewport sampling tab.
4. Implemented upscale_filter usage in ViewportEngine and ViewportEngine2.

RPRBLND-1664: Add support for ML denoiser + upscale

---

src/rprblender/properties/render.py

RIF macOS has an issue with upscaling filter.
Disable viewport upscaling on macos
@bnagirniak I think we should still be doing viewport denoising but that is a deeper change.

Disable upscaler on MACOS

---

cmd_tools/create_sdk.py

Due to the changes in RIF libraries(dropped support for Ubuntu18) the Ubuntu18 binaries weren't updated. The Ubuntu20 binaries should be used instead.
- Fixed image filters on Ubuntu20.
- changed path to the RIF libraries in plugin builder

Fixed RIF libraries for Ubuntu

---

src/bindings/pyrpr/src/pyrprapi.py

Updated SDK version to 2.2.4
- RPR SDK updated to version 2.2.4.
- updated SDK submodule;
- added more Baikal header definitions to the wrapper builder exclude list.

Updated RPR SDK to version 2.2.4

---

src/rprblender/engine/preview_engine.py
src/rprblender/engine/render_engine.py
src/rprblender/engine/viewport_engine.py
src/rprblender/ui/world.py

PURPOSE
There is errors in console during rendering and UI operations if we delete world light from scene.
No more errors if world light doesn't exist.
Added checks for world light everywhere it is needed

RPRBLND-1896: Case scene.world == None isn't handled by plugin.

---

src/bindings/pyrpr/src/pyhybrid.py
src/bindings/pyrpr/src/pyhybridpro.py

Fix exception for unsupported material nodes.
Fixed exception for unsupported material nodes.
Added implementation of set_id method for 'EmptyMaterialNode'.

RPRBLND-2072: AttributeError: 'EmptyMaterialNode' object has no attribute '_handle_ptr'.

---

src/rprblender/nodes/blender_nodes.py

Fixes the Vector Mapping Rotation input node not working.
The Vector Mapping Rotation input node will now work as expected
Changed "get_input_default" to "get_input_value" which polls the value on the input of the node instead of the default value in the node
Tested Locally on a single project. Everything works as expected

Fix: ShaderNodeMapping Rotation Input Value (Fixes #606)

---

src/rprblender/nodes/blender_nodes.py

Pingpong math is broken when the input is less than zero
Pingpong math will match cycles/eevee
Added an abs to the initial subtraction in the pingpong math
The center of the render is UV 0
Setup 
Sample file
[prorenderpingpong.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11338633/prorenderpingpong.zip)
Prorender:
Eevee:
Cycles:
Prorender After this patch:

Fix pingpong math

---

src/rprblender/properties/view_layer.py

Need to deactivate old denoiser options, because this option was hidden in UI, but is still active and the user can't switch off or set up.
Denoiser doesn't affect the final render result in old scenes.
Permanently deactivate denoiser "enable" property.
[Ticket](https://amdrender.atlassian.net/browse/RPRBLND-2291) to remove redundant 'denoiser' code.

RPRBLND-2290: deactivate hided denoiser options

---

src/rprblender/nodes/rpr_nodes.py

Add RPR NormalMap node export for HybridPro
Added RPR NormalMap node export for HybridPro
Added `export_hybridpro` for RPR NormalMap node

Add RPR NormalMap node export for HybridPro

---

src/bindings/pyrpr/src/pyrprapi.py
src/rprblender/engine/preview_engine.py
src/rprblender/engine/render_engine.py
src/rprblender/engine/viewport_engine.py
src/rprblender/properties/render.py
src/rprblender/ui/render.py

Core submodules has to be updated.
Added support for `RPR Toon` backward compatibility `Render Properties tab -> Settings -> Final -> Use Legacy RPR Toon`.
Updated latest Core to 3.1.4.
Adjusted build script.
Added UI checkbox `Use Legacy RPR Toon` to support `RPR_CONTEXT_NORMALIZE_LIGHT_INTENSITY_ENABLED`
By default `Use Legacy RPR Toon = False -> RPR_CONTEXT_NORMALIZE_LIGHT_INTENSITY_ENABLED = 1`

Updated latest Core 3.1.4

---

BlenderPkg/build_linux.sh
README-LNX.md
build.cmd
build.py
build.sh
run_blender_with_rpr_Ubuntu.sh
src/bindings/pyrpr/rpr.py
src/rprblender/export/mesh.py
src/rprblender/nodes/blender_nodes.py

Add support for blender 4.1
User are able to install plugin on blender 4.1
Use blender new API in mesh.py
Switch to python 3.11 (blender switched to python 3.11)
Fix linux/windows build scripts
Update linux readme
* Linux build doesn't work (yet) due to issue in rpr shaders
* Windows: plugin doesn't initialize on systems with APU's and GPU (read - on some laptops). Unsupported GPU make's plugin "stuck" in initialization.
* Windows: Pre-RDNA gpu's doesn't work

Blender 4.1
